# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'CLFoundationExample' do

  pod 'Masonry'
  pod 'CLUIKit'
end
